services:
  nginx:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - backend-network
    depends_on:
      - user-service
      - product-service
      - order-service
    restart: always

  user-service:
    build: ./backend/user-service
    networks:
      - backend-network
    deploy:
      replicas: 2

  product-service:
    build: ./backend/product-service
    networks:
      - backend-network
    deploy:
      replicas: 2
    depends_on:
      - rabbitmq
    restart: always

  order-service:
    build: ./backend/order-service
    networks:
      - backend-network
    deploy:
      replicas: 2
    depends_on:
      - rabbitmq
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - backend-network
    volumes:
      - mongodb-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
